#!/bin/bash
version=${1:?usage: $0 <php version (e.g. 56)>}

source ./spec.sh

it_should_have_the_latest_php_image_version() {
  tmp_dir=$(mktemp -d .php-compare-${version}.XXXXXX)
  cd ${tmp_dir}
  ../create-php-dockerfile ${version}
  cp -a ../php-${version}-container-files/meteogroup php-${version}-container-files/

  rm *.orig *.bak

  for f in *
  do
    echo "verifying $f"
    if ! diff -r ${PWD}/$f ${PWD}/../$f
    then
      echo "$f was updated in the original php image"
      exit 1
    fi
  done

  rm -rf ${tmp_dir}
}

run_tests
