#!/bin/bash -ex
# this file automatically creates the Dockerfile for our php-fpm-memcached image
# run it and check the diff of Dockerfile.php-fpm-memcached carefully

version=$1
root=${PWD}

if [ -z "${version}" ]
then
  echo "usage: $0 <php-version> (php version being one of 55, 56, 70)"
  exit 1
fi

final_dockerfile=${PWD}/Dockerfile.php:${version}
final_dev_dockerfile=${PWD}/Dockerfile.php-dev:${version}

cat  << EOF| tee "${final_dockerfile}.orig" > "${final_dockerfile}"
# this is a Dockerfile that flattens out https://github.com/million12/docker-nginx-php / branch php56
# and uses meteogroup/centos:7 as a base
FROM meteogroup/centos:7

EOF

container_files_dir=php-${version}-container-files
rm -rf ${container_files_dir}
mkdir -p ${container_files_dir}

tmp_dir=$(mktemp -d .php-${version}-XXXXX)
cd ${tmp_dir}

function include_dockerfile_repo() {
  local url=$1
  local branch=$2

  git clone ${branch:+-b ${branch}} --depth=1 ${url}

  (
    set -xe
    cd $(basename ${url})
    cp -a container-files ${root}/${container_files_dir}/$(basename ${url})
    echo -e "\n\n########################### ${url}" | tee -a "${final_dockerfile}.orig" >> "${final_dockerfile}"
    cat Dockerfile >> "${final_dockerfile}.orig"
    cat Dockerfile | grep -v "^FROM" \
                   | grep -v "^MAINTAINER" \
                   | grep -v "^ENTRYPOINT" \
                   | grep -iv "ruby" \
                   | grep -iv "source" \
                   | grep -iv "npm" \
                   | grep -iv "gem" \
                   | grep -iv "make" \
                   | grep -iv "redis" \
                   | sed 's/ mysql //g' \
                   | sed 's/.*ImageMagick.*/yum install -y "ImageMagick GraphicsMagick" \&\& \\/g' \
                   | sed "s#ADD *container-files#ADD ${container_files_dir}/$(basename ${url})#g" >> "${final_dockerfile}"
  )
}

include_dockerfile_repo https://github.com/million12/docker-centos-supervisor
include_dockerfile_repo https://github.com/million12/docker-nginx
include_dockerfile_repo https://github.com/million12/docker-nginx-php php${version}

echo -e "\n\n########################### HA! ... our own stuff" | tee -a "${final_dockerfile}.orig" >> "${final_dockerfile}"
echo "RUN yum update && yum install -y php-memcache php-memcached" | tee -a "${final_dockerfile}.orig" >>  "${final_dockerfile}"

cp "${final_dockerfile}" "${final_dev_dockerfile}"
cat >> "${final_dev_dockerfile}" << EOF
RUN bash -exc "curl -O http://getcomposer.org/composer.phar && mv composer.phar /usr/bin/composer && chmod +x /usr/bin/composer; \\
               yum install -y git; \\
               bash <(curl -f http://rpmrepo.de.meteogroup.net/sourcebin/haarp-install)"
EOF
rm -rf ${tmp_dir}
